### ISSUE TITLE
Sort stock card by ticker/symbol

### ISSUE THREAD

**Issue by kasulk** [kasulk/ursula#20]
## Value proposition

As a user
I  can sort the stock list by the ticker/symbol
So that I can find a stock I'm looking for faster

## Acceptance criteria

- [x] A sort-dropdown is displayed on top of the stock list view
- [x] The user can sort by tickers ascending
- [x] The user can sort by tickers descending

## Tasks

- [x] Create SortDropdown component (on top of the stock list)
- [x] Create a dropdown-menu with 2 options
- [x] Lift chosen value up to Home-Page
- [x] Sort stocks[{}] with sort() method based on chosen value
