### ISSUE TITLE
Add (colored) distance of (fair) values to current price (after actual values)

### ISSUE THREAD

**Issue by kasulk** [kasulk/ursula#24]
## Value proposition

As a user
I can see the distance of particular (calculates) values to the current stock price
So that I have a nice quick overview over the value of stock compared to its current price

## Description

e.g. BookValue: 69.35, current Price: 73.80 >>> 100 * (69.35-73.80) / 73.80
--> "BookValue: 69.35 `-6%`"

## Acceptance criteria

- [ ] Distance BookValue to current price is displayed as % after the BookValue value
- [ ] Distance FairValue to current price is displayed as % after the FairValue value
- [ ] Distance Analyst Target Price to current price is displayed as % after the Analyst Target Price value

## Tasks

- [ ]
