### ISSUE TITLE
See Icon of corporation

### ISSUE THREAD

**Issue by kasulk** [kasulk/ursula#25]
## Value proposition

As a user
I  can see the company logo (next to the company name)
So that I can quicker identify a stock (if I know the logo, else it's just a nicer UX)

## Acceptance criteria

- [ ] Company logos are displayed (next to the company name) 

## Tasks

- [ ] get company logo links from twelve data
- [ ] store the links in the demostocks.json (as 'LogoLink')
