### ISSUE TITLE
Set up Next Auth

### ISSUE THREAD

**Issue by kasulk** [kasulk/ursula#32]
## Value proposition

As a user
I  can login with my GitHub credentials
So that I can save my personal favorite stocks

## Acceptance criteria

- [ ] The user can log in with GitHub credentials
- [ ] The user has to be logged in to mark stocks as favorite
- [ ] If the user isn't logged in, no favorite buttons and favorite filter button is displayed
- [ ] If the user is logged in, favorite buttons and favorite filter button is displayed

## Tasks

- [ ] Read again about Next Auth
- [ ] Make it happen 💪
