### ISSUE TITLE
Fetch data of 3000 stocks from API and store the it in the db

### ISSUE THREAD

**Issue by kasulk** [kasulk/ursula#41]
## Value proposition

As a user
I  can always see relatively current stock market data
So that I can work with current data

## Description

The free version of the API allows only 5 API requests per minute and 500 per day.
In order get the data of all the stocks in the Russell 3000 Index the script is run in the terminal to make a request every 61 seconds and stores the retrieved data in the db.
Then the Next-App can retrieve the data from the db.

## Acceptance criteria

- [ ] A fetch request is started once per minute
- [ ] The fetched data is stored in the db
- [ ] Fetch/renew the oldest data first

## Tasks

- [ ] npm i node-fetch (for fetching from script in terminal)
- [ ] Find and scrape a list of the members of the Russell3000 Index
- [ ] Add a timestamp to each ticker
- [ ] Create a seperate db collection
- [ ] Save data in db
- [ ] Check the data in the db and fetch 5 stocks with oldest data
(if there is no oldest data, fetch by ticker ascending first)
- [ ] Change string numbers to numbers
- [ ] Create another db collection for the prices
- [ ] Do the same to fetch the prices
