### ISSUE TITLE
Fix: Create 2 dropdowns for sorting functionality (sort criteria and sort direction)

### ISSUE THREAD

**Issue by kasulk** [kasulk/ursula#56]
## Value proposition

As a user
I  can choose the sort criteria in one dropdown and the direction in an other dropdown
So that change the sorting more quickly

## Acceptance criteria

- [ ] 2 sort dropdowns are displayed in the header
- [ ] 1 for choosing the sort direction (ascending/descending)
- [ ] 1 for choosing the sort criteria (e.g. ticker, market cap, dividend yield...)

## Tasks

- [ ]
