### ISSUE TITLE
Sort by 52 week "Bruchwert" or Div%

### ISSUE THREAD

**Issue by kasulk** [kasulk/ursula#7]
## Value proposition

As a user
I  can sort the stock list by the Bruchwert or the Div%
So that I can see which stock could currently be cheap compared to its 52Week-Range and which stocks are currently paying the highest Div%.

## Description

Bruchwert is a % value that shows how far away the current stock price is from its 52Week-Low 

## Acceptance criteria

- [x] 52week Bruchwert is displayed in stock cards
- [x] Div% is displayed in stock cards
- [x] User can sort the stock list by 52week Bruchwert
- [x] User can sort the stock list by Div%

## Tasks

- ~~Turn number-strings in db demostocks manually to numbers~~
- ~~Create a StockKeyValue component and move the render logic and HTML elements there~~
- [x] Calculate and render the values to the stock card
- [x] Create Div% option in SortDropdown
- [x] Create Bruchwert% option in SortDropdown
- [x] Calculate Bruchwert
- [x] Move the function declarations to utils folder
